# Generated by Django 4.0.4 on 2022-05-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_service', '0002_messages_user_to_alter_messages_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
