# Generated by Django 4.0.4 on 2022-05-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_service', '0003_alter_messages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Review'), (1, 'Blocked'), (2, 'Correct')]),
        ),
    ]
