# Generated by Django 4.0.4 on 2022-05-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_service', '0004_alter_messages_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Review'), (1, 'Blocked'), (2, 'Correct')], default=0),
        ),
    ]
